CREATE DATABASE IF NOT EXISTS OFICINA;
USE OFICINA;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE_DO_CLIENTE INT NOT NULL,
EMAIL_DO_CLIENTE VARCHAR(100),
DATA_DE_NASCIMENTO INT NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS VEICULOS (
ID_VEÍCULOS INT AUTO_INCREMENT PRIMARY KEY,
NOME_DO_PROPRIETARIO VARCHAR(70) NOT NULL,
ESTADO_DO_VEICULO ENUM ('BOM','RUIM') NOT NULL,
PESO_DO_VEICULO INT NOT NULL,
DOCUMENTAÇÃO_DO_VEICULO VARCHAR(90) NOT NULL,
ANO_DE_FABRICAÇÃO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MARCA (
ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
ORIGEM_DA_MARCA VARCHAR(50) NOT NULL,
NOEM_DA_MARCA VARCHAR(50)  NOT NULL,
ANO_DE_FABRICAÇÃO INT NOT NULL,
TIPO_PRODUTO VARCHAR(30) NOT NULL,
LOCALIZAÇÃO_DA_MARCA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MODELOS(
ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
NOEM_DO_MODELO VARCHAR(80) NOT NULL,
COR_DO_MODELO VARCHAR(40),
TIPO_DO_MODELO VARCHAR(90) NOT NULL,
NOME_DO_MARCA VARCHAR(80) NOT NULL,
DATA_DA_FABRICAÇÃO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
CARGO_DO_FUNCIONARIO VARCHAR(30) NOT NULL,
SALARIO DECIMAL(5,2)default 0.0,
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME_DO_FUNCIONARIO VARCHAR(80) NOT NULL,
DATA_DE_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS SERVIÇOS (
ID_SERVIÇOS INT AUTO_INCREMENT PRIMARY KEY,
TURNOS VARCHAR(10) NOT NULL,
CARGO VARCHAR(15) NOT NULL,
DATA_DE_CADA_SERVIÇO DATE NOT NULL,
PREÇO_DE_CADA_SERVIÇO INT NOT NULL,
NOME_DOS_SERVIÇOS VARCHAR (60) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEÇAS (
ID_PEÇAS INT AUTO_INCREMENT PRIMARY KEY,
PESO_DA_PEÇA INT NOT NULL,
TIPO_DE_PEÇA VARCHAR (50) NOT NULL,
NOME_DA_PEÇA VARCHAR(50) NOT NULL,
PREÇO_DA_PEÇA INT NOT NULL,
TAMANHO_DA_PEÇA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE_PARA_CONTATO VARCHAR(15),
EMAIL VARCHAR(100),
MARCAS_FORNECEDORAS VARCHAR(50) NOT NULL,
NOME_DO_FORNECEDOR VARCHAR(80) NOT NULL,
CNPJ_DA_EMPRESA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDENS_DE_SERVIÇO (
ID_SERVIÇOS INT AUTO_INCREMENT PRIMARY KEY,
NOME_RESPONSÁVEL VARCHAR(20) ,
VALOR_TOTAL INT NOT NULL,
DATA_ABERTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DESCRIÇÃO_DA_ORDEM VARCHAR(100),
DATA_FECHAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY,
DATA_DO_PAGAMENTO DATE NOT NULL,
FORMA_DE_PAGAMENTOO VARCHAR(20) NOT NULL,
VALOR_DO_PAGAMENTO INT NOT NULL,
CPF VARCHAR(14) NOT NULL,
PARCELAMENTO ENUM ('SIM','NÃO') NOT NULL
);

SHOW TABLES;

SHOW DATABASES;

ALTER TABLE CLIENTES ADD ITEM_COMPRADO VARCHAR(30);
ALTER TABLE CLIENTES DROP COLUMN ITEM_COMPRADO;

ALTER TABLE VEICULOS ADD LOCAL_FABRICADO VARCHAR(100) NOT NULL;
ALTER TABLE VEICULOS DROP COLUMN LOCAL_FABRICADO;

ALTER TABLE MARCAS ADD LOCAL_ORIGEM VARCHAR(100) NOT NULL;
ALTER TABLE MARCAS DROP COLUMN LOCAL_ORIGEM;

ALTER TABLE MODELOS ADD PRECO DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE MODELOS DROP COLUMN PRECO;

ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100);
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;





RENAME TABLE MODELOS TO MODELOS_FAB;


